### ISSUE TITLE
Remove M0

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#1]
M0 is 'none' almost everywhere and it can be derived from PD, so I would remove it

**Comment by sriosq** [comment]
Thank you for the feedback @jcohenadad. It has been addressed.

**Comment by jcohenadad** [comment]
Here is where it has been addressed: https://github.com/shimming-toolbox/tissue-to-MRproperty/commit/92e767ecd3b4930f9ddb3692df7b95873949808b

@sriosq always good practice to refer to the commit in comments
