### ISSUE TITLE
Adding the option to provide a custom dictionary

### ISSUE THREAD

**Issue by CharlesPageot** [shimming-toolbox/tissue-to-MRproperty#10]
## Context
In my project, I need to generate fieldmaps based on the T1w images of the `whole-spine` dataset. The different labels for this project were obtained using various tools (see [#6](https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft/issues/6)). The goal would be to use this repo and the [susceptibility-to-fieldmap-fft](https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft) code to create the susceptibility distributions and to simulate the $\Delta B_0$.

## New feature idea
Since I have custom labels (i.e coming from different tools) I would need to have the possibility to input my own (segment #, name) pairs. In the `tissue_to_MR` command, I propose to add an additional _custom_ choice for the --segtool option. If this option is selected, the user would provide a dictionary (for example as a .txt file) to generate the volume.

## Implementation
If this feature was not already being developed, I could create a branch to start the implementation. What do you think @sriosq ?

**Comment by sriosq** [comment]
After discussing about it. It would be better to add the proposed dictionary as a new tool on the code. As creating a "custom" option will be time consuming to implement and, adding new "tools" to the converter is very easy and straigthforward. Thanks! @CharlesPageot
