### ISSUE TITLE
Add susceptibility values in the table

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#2]

**Comment by jcohenadad** [comment]
> Added the look-up table for the susceptibility values being used

where is this added? always refer to the commit SHA in comments please, otherwise we cannot review

**Comment by jcohenadad** [comment]
i assume this is the commit in question: https://github.com/shimming-toolbox/tissue-to-MRproperty/commit/92e767ecd3b4930f9ddb3692df7b95873949808b

the problem here is that you created another table-- why not simply adding a column only the existing table?

**Comment by sriosq** [comment]
Working on it

**Comment by sriosq** [comment]
I initially had 2 separated tables but now its a new column here: 4de1a893c9ce364a0937832c4c62613784a75b07 
Apologies for not directing to it before @jcohenadad

**Comment by sriosq** [comment]
Task completed. Closing the issue
