### ISSUE TITLE
Consider renaming repository

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#3]
I find the term 'segmentation' non-specific. Eg: there could be segmentation of a sub-region inside a tissue, but that's not really what the code is doing.

Also, I find the term 'converter' unecessary given the presence of the word "to". 

I suggest renaming to something like `tissue-to-MRproperty`.

**Comment by sriosq** [comment]
I agree and this sounds like a better proper name for the codes purpose. Working on it

**Comment by po09i** [comment]
Done :)

**Comment by sriosq** [comment]
Action done. Closing the issue.
