### ISSUE TITLE
Create CLI and add instructions how to use the code

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#4]
I suggest creating a command line script interface (CLI) that can be called from the Terminal, and instructions on how to use the script in the README.

Similar to what was done for https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft?tab=readme-ov-file#usage

**Comment by sriosq** [comment]
Currently working on adding this to the code and will also add instructions to the README file. Thanks

**Comment by sriosq** [comment]
Initial working CLI recently pushed. See https://github.com/shimming-toolbox/tissue-to-MRproperty/commit/1aad13159453e992d1a62a158811ef776d7582c2.
Working on adding a description to the README file later tonight.

**Comment by sriosq** [comment]
Here is the link for the commit: https://github.com/shimming-toolbox/tissue-to-MRproperty/commit/6c2cfb8f041cea93c2fc2df0500d6d940f2bfa1b 
Thanks for the recommendation, it is a great idea to implement this. @jcohenadad

**Comment by jcohenadad** [comment]
Someone else should try your CLI and instructions, eg @CharlesPageot

**Comment by CharlesPageot** [comment]
I cloned the repo, followed the instructions and it works

**Comment by sriosq** [comment]
Recently updated to work with pip install here 96803c64a03616a6b8335203237f14615aeaea57 . Works correctly. Closing issue. Thanks for the help and testing!
