### ISSUE TITLE
Remove dependency to SCT

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#6]
Code should not be dependent on SCT. All you should need to run the code is Python and a label file.

https://github.com/shimming-toolbox/segmentation-to-MRproperties-converter/blob/2eef20de25762b53972042b127bdeab32f968b46/interactive.ipynb#L206-L210

**Comment by sriosq** [comment]
Hello, the code is not dependent of SCT. I added that section to explain how one can add labels, and as an example, I used SCT. Perhaps I should re-write the text? Thank you :)

**Comment by jcohenadad** [comment]
In general it is a good idea to avoid 3rd party dependency when creating a tutorial for a software-- eg what if a user only does brain studies, why would you ask them to install SCT?

**Comment by sriosq** [comment]
Okay I see. In my example I used _sct_maths_ to workaround adding the labels but I see that this could be done in many different ways hence SCT shouldn't be a requirement. Do you recommend taking out the example code and leaving just an explanation on the README file?

**Comment by jcohenadad** [comment]
> Do you recommend taking out the example code and leaving just an explanation on the README file?

Yes-- or you could show how to do is with a simple image editor (eg ITKsnap, Slicer)

**Comment by sriosq** [comment]
I did some changes to the explanation of adding a label here: https://github.com/shimming-toolbox/tissue-to-MRproperty/commit/a4688ef4d139ad6cc58a192cbe3f3608915750e8
I specify that I use SCT only as an example and I elaborate more on whats the strategy to adding the labels and that it can be done with any tool. Looking forward to your opinion on this, thanks again for the feedback! @jcohenadad
