### ISSUE TITLE
Do not use capital letter for python file names

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/tissue-to-MRproperty#7]
https://github.com/shimming-toolbox/segmentation-to-MRproperties-converter/blob/main/functions/Volume.py

see [PEP8](https://peps.python.org/pep-0008/)

**Comment by sriosq** [comment]
Thank you for the feedback! I had never though of this. Solved and taking this into account further down the line @jcohenadad

**Comment by sriosq** [comment]
Task ready. Closing the issue
